plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.2'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.team.arium'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-web-services'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.session:spring-session-core'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	
    //Spring Security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	testImplementation 'org.springframework.security:spring-security-test'
		
	//Database	
	//MySQL
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.4'
	runtimeOnly 'com.mysql:mysql-connector-j'
	testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:3.0.4'
	
	//PostgreSQL	
	implementation 'org.postgresql:postgresql:42.7.3'

	//Sping framework
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    
    //Thymeleaf
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	
    //Httpservlet request, respons
	compileOnly 'javax.servlet:javax.servlet-api:4.0.1'
           
    //JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	
	//lombok   
	compileOnly 'org.projectlombok:lombok' //코드 작성을 줄여 주는 Lombok 애너테이션(@Getter, @Setter 등)
	//컴파일러가 Lombok 애너테이션을 처리하도록 해 주는 설정으로, compileOnly와 함께 사용해야 애너테이션 생성자가 동작
	annotationProcessor 'org.projectlombok:lombok'
	
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	
	//fileupload
	implementation 'commons-fileupload:commons-fileupload:1.5'
	implementation 'commons-net:commons-net:3.11.1'
	implementation 'com.squareup.okhttp3:okhttp:4.12.0'
	implementation 'xalan:serializer:2.7.3'
	
}

tasks.named('test') {
	useJUnitPlatform()
}
