spring.application.name=com.team.arium

#Server
server.port=8082
server.servlet.encoding.charset=utf-8
server.servlet.encoding.force-response=true
server.servlet.encoding.enabled=true
spring.devtools.restart.enabled=true

#session셋팅 : 1800 = 30분
server.servlet.session.timeout=60m

#File
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB



# 추가 설정 (파일 개수 제한)
spring.servlet.multipart.file-size-threshold=0
spring.servlet.multipart.resolve-lazily=false

# Tomcat 설정 (파일 개수 제한)
server.tomcat.max-http-form-post-size=100MB
server.tomcat.max-swallow-size=100MB
server.tomcat.max-connections=8192
server.tomcat.accept-count=100
server.tomcat.max-threads=200

#Thymeleaf
spring.thymeleaf.cache=false
#templates 디렉토리가 있는지 확인하는 구문 
spring.thymeleaf.check-template-location=true

spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=html
spring.thymeleaf.view-names=/*

spring.config.import=classpath:application-data.properties
